const state = [
  { country: "United States", label: "New York" },
  { country: "United States", label: "California" },
  { country: "United States", label: "Texas" },
  { country: "United States", label: "Florida" },
  { country: "United States", label: "Illinois" },
  { country: "Canada", label: "Ontario" },
  { country: "Canada", label: "Quebec" },
  { country: "Canada", label: "British Columbia" },
  { country: "Canada", label: "Alberta" },
  { country: "Canada", label: "Manitoba" },
  { country: "United Kingdom", label: "England" },
  { country: "United Kingdom", label: "Scotland" },
  { country: "United Kingdom", label: "Wales" },
  { country: "United Kingdom", label: "Northern Ireland" },
  { country: "United Kingdom", label: "London" },
  { country: "Australia", label: "New South Wales" },
  { country: "Australia", label: "Victoria" },
  { country: "Australia", label: "Queensland" },
  { country: "Australia", label: "Western Australia" },
  { country: "Australia", label: "South Australia" },
  { country: "France", label: "Paris" },
  { country: "France", label: "Provence-Alpes-Côte d'Azur" },
  { country: "France", label: "Occitanie" },
  { country: "France", label: "Auvergne-Rhône-Alpes" },
  { country: "France", label: "Normandy" },
  { country: "Germany", label: "Bayern" },
  { country: "Germany", label: "Nordrhein-Westfalen" },
  { country: "Germany", label: "Baden-Württemberg" },
  { country: "Germany", label: "Berlin" },
  { country: "Germany", label: "Lower Saxony" },
  { country: "Japan", label: "Tokyo" },
  { country: "Japan", label: "Kyoto" },
  { country: "Japan", label: "Osaka" },
  { country: "Japan", label: "Hokkaido" },
  { country: "Japan", label: "Hiroshima" },
  { country: "Japan", label: "Aichi" },
  { country: "Japan", label: "Fukuoka" },
  { country: "Japan", label: "Hyogo" },
  { country: "Japan", label: "Kanagawa" },
  { country: "Japan", label: "Miyagi" },
  { country: "Japan", label: "Nara" },
  { country: "Japan", label: "Niigata" },
  { country: "Japan", label: "Okayama" },
  { country: "Japan", label: "Shizuoka" },
  { country: "Japan", label: "Tochigi" },
  { country: "Japan", label: "Tokushima" },
  { country: "Japan", label: "Tottori" },
  { country: "Japan", label: "Toyama" },
  { country: "Japan", label: "Wakayama" },
  { country: "Japan", label: "Yamagata" },
  { country: "Japan", label: "Yamaguchi" },
  { country: "Japan", label: "Yamanashi" },
  { country: "Japan", label: "Nagasaki" },
  { country: "Japan", label: "Kumamoto" },
  { country: "China", label: "Beijing" },
  { country: "China", label: "Shanghai" },
  { country: "China", label: "Guangdong" },
  { country: "China", label: "Sichuan" },
  { country: "China", label: "Zhejiang" },
  { country: "India", label: "Maharashtra" },
  { country: "India", label: "Tamil Nadu" },
  { country: "India", label: "Uttar Pradesh" },
  { country: "India", label: "Karnataka" },
  { country: "India", label: "Gujarat" },
  { country: "Brazil", label: "São Paulo" },
  { country: "Brazil", label: "Rio de Janeiro" },
  { country: "Brazil", label: "Minas Gerais" },
  { country: "Brazil", label: "Bahia" },
  { country: "Brazil", label: "Rio Grande do Sul" },
];

export default state;
